### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by analyserdmz** [limbenjamin/ReverseShellDll#1]
How to compile with VC++ 2008 for minimum dependencies?

**Comment by limbenjamin** [comment]
Under Configuration Properties --> C/C++ --> Code Generation, change the "Runtime Library" field to "Multi-Threaded (/MT)"

https://stackoverflow.com/questions/37398/how-do-i-make-a-fully-statically-linked-exe-with-visual-studio-express-2005
